# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f46ffb06a5ca34230d94ea5331a6e9b1007764bca36389a5b70f4d0b845c39d19396824d818616cf241b6dec807225ad055f9d5a556de6b5e59979d1e0238fa

test:
  secret_key_base: e7d7fb1c37f9d2013f6e30e5c1dd89d2400a1e69a6655bd42e25c94f7dfb238093034251975700e2c181f5f917e851fe9346381ff533673c8227954bb95f0029

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
